### ISSUE TITLE
License file / GNU naming

### ISSUE THREAD

**Issue by euank** [kusma/rocket#37]
I see that the "COPYING" file contains an MIT licence (right?). It would be easier to find it if it were named `LICENSE` instead, but at the very least the license should also be referenced in the readme.

I'm also confused as to why it's name `GNU Rocket` when I don't see any relation to GNU and it's not GPL'd, as best as I can tell, so a quick bit of explanation around that might help other readers who are confused.

Thanks!

**Comment by kusma** [comment]
The license is the [Zlib-license](https://opensource.org/licenses/Zlib), and the reason for `COPYING` instead of `LICENSE`, is that this used to be the defacto standard place to put license files when the license file were introduced. I'm not married to the name, and IIRC even Github doesn't really understand the license unless it's renamed somehow. So I'm open to patches on this.

The "GNU"-part of the name is an old. silly joke. It's not using any GNU licenses or is in any way affiliated with the GNU project. I also wouldn't mind patches to get rid of the GNU-part of the name, as long as it doesn't affect backwards compatibility (for instance, some QSettings stuff might need some fallback-shims to the old location if moved).

**Comment by kusma** [comment]
Just to be clear, my intention is to do at least the latter part, as I really don't want there to be any pretend-affiliation with the GNU project. But if someone beats me to it, I won't mind it ;)

**Comment by euank** [comment]
The shortest/easiest fix I think is just clarifying both of these points in the readme.

If it contained a `License` or `Copying` header at the bottom that said essentially "This code is provided under the zlib license, more information here<COPYING file link>", and somewhere in the introduction clarified that there was no affiliation with the well-known GNU project, that would be enough to dodge the confusion I had. Thanks for the clarification here.

**Comment by kusma** [comment]
This should all be fixed now. I also added a Zlib-license badge to the README.md for extra clarity.
